version: '3.7'

volumes:
  autobase-db:

services:
  autobase-postgres:
    container_name: autobase-db
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: autobase-db
    volumes:
      - autobase-db:/var/lib/postgresql/data
    ports:
      - "6767:5432"